In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
data = {'name':['alice','bob'],'age':[25,30]}

In [8]:
df = pd.DataFrame(data)

In [6]:
last =[['alice',25],['bob',30]]

In [9]:
df.head()

    name  age
0  alice   25
1    bob   30

In [10]:
df.tail()

    name  age
0  alice   25
1    bob   30

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      str
 1   age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [12]:
df.describe()

             age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [13]:
df['name']

0    alice
1      bob
Name: name, dtype: str

In [14]:
df[['name','age']]

    name  age
0  alice   25
1    bob   30

In [15]:
df.loc[0]

name    alice
age        25
Name: 0, dtype: object

In [16]:
df.iloc[1]

name    bob
age      30
Name: 1, dtype: object

In [17]:
df[df['age']>25]

  name  age
1  bob   30

In [18]:
df['gender'] = ['f','m']

In [19]:
df.drop('age',axis=1,inplace=True)

In [20]:
df.isnull()

    name  gender
0  False   False
1  False   False

In [21]:
df.dropna()

    name gender
0  alice      f
1    bob      m

In [22]:
df.fillna(0)

    name gender
0  alice      f
1    bob      m

In [26]:
df1 = pd.DataFrame({'key':['A','B','C'],'value1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'],'value2':[4,5,6]})

In [27]:
pd.merge(df1,df2,on='key')

  key  value1  value2
0   A       1       4
1   B       2       5

In [29]:
df1.join(df2,lsuffix='_left',rsuffix='_right')

  key_left  value1 key_right  value2
0        A       1         A       4
1        B       2         B       5
2        C       3         D       6

In [31]:
import os

In [32]:
os.getcwd()

'C:\\Users\\User'

In [33]:
os.listdir()

['.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.vscode',
 '.vscode-shared',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{fdb70ad5-e0ea-11ef-bc41-cc6b1e8404b8}.TM.blf',
 'NTUSER.DAT{fdb70ad5-e0ea-11ef-bc41-cc6b1e8404b8}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{fdb70ad5-e0ea-11ef-bc41-cc6b1e8404b8}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [39]:
df = pd.read_csv('data.csv')

In [40]:
df.to_csv('output.csv',index=False)

In [42]:
df.sort_values('age')

    name  age
0  Alice   25
1    Bob   30

In [43]:
df['age'].apply(lambda x: x+1)

0    26
1    31
Name: age, dtype: int64

In [46]:
df['name'].unique()

<StringArray>
['Alice', 'Bob']
Length: 2, dtype: str

In [47]:
df['age'].value_counts()

age
25    1
30    1
Name: count, dtype: int64